version: 0.2

phases:
 install:
   commands:
     - echo Entered the install phase...
     - apt-get update
     - apt-get install awscli jq ansible -y
 build:
   commands:
     - echo Build started on `date`
     - export ANSIBLE_PLAYBOOK_PATH=ansible-cloudformation-deletion.yaml
     - sh CloudFormation/CodeBuild/ansible-cft-call.sh 
 post_build:
   commands:
     - echo Build completed on `date`     