---
- name: provision stack deletion
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: tear down old deployment
    cloudformation:
    stack_name: "ansible-cloudformation"
    state: "absent"
    region: "us-east-1"